PassRegistration/Models/PassRegistration.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;


namespace PassRegistration.Models
{
    public class PassRegistration
    {
        
        public int Id { get; set; }
        public string UserName { get; set; }
        [Required]
        public string Name { get; set; }
        public int NumberInHouse { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public int ZipCode { get; set; }
        [Required]
        public string PhoneNumber { get; set; }
        [Required]
        public string Email { get; set; }
        public string Status { get; set; }

        public PassRegistration()
        {
            UserName = "Not Provided.";
            Name = "Not Provided.";
            NumberInHouse = 0;
            Address = "Not Provided.";
            City = "Not Provided.";
            ZipCode = 00000;
            PhoneNumber = "Not Provided.";
            Email = "Not Provided.";
            Status = "Pending.";
        }
    }

}

PassRegistration/Controllers/PassRegistrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PassRegistration.Controllers
{
    using System.Linq;
    using System.Web.Mvc;
    using PassRegistration.Models;
    using System.ComponentModel.DataAnnotations;

    public class PassRegistrationController : Controller
    {
        private ApplicationDbContext _dbContext;

        public PassRegistrationController()
        {
            _dbContext = new ApplicationDbContext();
        }

        // GET: Videos
        public ActionResult Index()
        {
            var registrations = _dbContext.PassRegistrations.ToList();

            return View(registrations);
        }

        public ActionResult AdminPass1()
        {
            var registrations = _dbContext.PassRegistrations.ToList();

            return View(registrations);
        }

        public ActionResult New()
        {
            return View();
        }

        public ActionResult Add(PassRegistration registration)
        {
            try
            {
                _dbContext.PassRegistrations.Add(registration);
                _dbContext.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            catch (Exception error)
            {
                return View("New");
            }
        }

        public ActionResult Delete(int id)
        {
            var registration = _dbContext.PassRegistrations.SingleOrDefault(v => v.Id == id);

            if (registration == null)
                return HttpNotFound();

            return View(registration);
        }

        [HttpPost]
        public ActionResult DoDelete(int id)
        {
            var registration = _dbContext.PassRegistrations.SingleOrDefault(v => v.Id == id);
            if (registration == null)
                return HttpNotFound();
            _dbContext.PassRegistrations.Remove(registration);
            _dbContext.SaveChanges();
            return RedirectToAction("Index");
        }



        public ActionResult Edit(int id)
        {
            var video = _dbContext.PassRegistrations.SingleOrDefault(v => v.Id == id);

            if (video == null)
                return HttpNotFound();

            return View(video);
        }

        public ActionResult Update(PassRegistration video)
        {
            var videoInDb = _dbContext.PassRegistrations.SingleOrDefault(v => v.Id == video.Id);

            if (videoInDb == null)
              return HttpNotFound(); 

           
            videoInDb.Name = video.Name;
            videoInDb.NumberInHouse = video.NumberInHouse;
            videoInDb.Address = video.Address;
            videoInDb.City = video.City;
            videoInDb.PhoneNumber = video.PhoneNumber;
            videoInDb.Email = video.Email;
            videoInDb.Status = video.Status;
            _dbContext.SaveChanges();

            return RedirectToAction("AdminPass1");
        }
    }
}

PassRegistration/Views/PassRegistration/AdminPass1.cshtml
@model IEnumerable<PassRegistration.Models.PassRegistration>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>

    tr:nth-child(even) {
        background-color: #eeeeee
    }
    tr:nth-child(odd) {
        background-color: #eeeeee
    }


</style>
    

@if (User.IsInRole("Admin"))
{


 <br />
 <br />
 <br />
 <br />
 <br />
 <br />
 <br />
 <br />

<center>
    <h2>Currently Registered Passes.</h2>
</center>

<center>
    <div class="container">
        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th># In HouseHold</th>
                    <th>Address</th>
                    <th>City</th>
                    <th>Phone No.</th>
                    <th>Email</th>
                    <th>Status</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var consultation in Model)
                {
                    <tr>
                        <td>@consultation.Name</td>
                        <td>@consultation.NumberInHouse</td>
                        <td>@consultation.Address</td>
                        <td>@consultation.City</td>
                        <td>@consultation.PhoneNumber</td>
                        <td>@consultation.Email</td>
                        <td>@consultation.Status</td>
                        <td>@Html.ActionLink("Edit", "Edit", new { id = consultation.Id })</td>
                        <td>@Html.ActionLink("Delete", "Delete", new { id = consultation.Id })</td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
</center>
}
else
{
    Response.Redirect("/home");
}

PassRegistration/Views/PassRegistration/Delete.cshtml
@model PassRegistration.Models.PassRegistration

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <br />
    <br />
    <br />

    <h2>Delete</h2>

    <p>
        Are you sure you would like to delete this pass?
    </p>
    <ul>
        <li>Name: @Model.Name</li>
        <li>Number in House: @Model.NumberInHouse</li>
        <li>Address: @Model.Address,@Model.ZipCode</li>
        <li>City: @Model.City</li>
        <li>Phone Number: @Model.PhoneNumber</li>
        <li>Email: @Model.Email</li>
    </ul>

    @using (Html.BeginForm("DoDelete", "PassRegistration", FormMethod.Post))
    {

        @Html.HiddenFor(m => m.Id)
        <input type="submit" class="btn btn-danger" value="Yes, Delete it!" />
        @Html.ActionLink("No, back to passes", "AdminPass1")
    }

PassRegistration/Views/PassRegistration/Edit.cshtml
@model PassRegistration.Models.PassRegistration

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@if (User.IsInRole("Admin"))
{

<div class="col-lg-2">
    <br />
    <br />
    <br />

</div>

<div class="col-lg-4">
    <br />
    <br />
    <br />
    <br />
    <h2>New Registration</h2>


    @using (Html.BeginForm("Update", "PassRegistration", FormMethod.Post, new { @class = "form" }))
    {
        <div class="form-group">
            @Html.LabelFor(m => m.Name)
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Address)
            @Html.TextAreaFor(m => m.Address, new { @class = "form-control", rows = 4 })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.NumberInHouse)
            @Html.TextAreaFor(m => m.NumberInHouse, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.City)
            @Html.TextBoxFor(m => m.City, new { @class = "form-control" })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.PhoneNumber)
            @Html.TextAreaFor(m => m.PhoneNumber, new { @class = "form-control", rows = 4 })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Email)
            @Html.TextAreaFor(m => m.Email, new { @class = "form-control" })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Status)
            @Html.TextAreaFor(m => m.Status, new { @class = "form-control" })
        </div>

        @Html.HiddenFor(m => m.Id)
        <input type="submit" class="btn btn-primary" value="Save" />

    }
</div>


<div class="col-lg-4">
    
    <br />
    <br />
    <br />
    <br />
    <br />

    <div class="form-group">
    </div>
        <br />
        <h3>Name</h3>
        <p>Pass Holders Name, First-Last Format</p>
    <div class="form-group">
    </div>
        <h3>Adress</h3>
        <p>Pass holders Adress, Street-Number format.</p>
    <div class="form-group">
    </div>
        <br />
        <br />
        <h3>Number In House</h3>
        <p>Number of people in Pass Holders house.</p>
    <div class="form-group">
    </div>
        <h3>City</h3>
        <p>City Pass Holder lives in.</p>
    <div class="form-group">
    </div>
        <br />
        <h3>Phone Number</h3>
        <p>Pass Holders phone number. xxx-xxx-xxxx Format.</p>
    <div class="form-group">
        <br />
        <br />
        <h3>Email</h3>
        <p>Pass Holders email.</p>
    </div>
    <div class="form-group">
        <h3>Status</h3>
        <p>Pass Holders pass status. Approved, Pending, Needs Payment</p>
    </div>


</div>

<div class="col-lg-2">

 </div>
}
else
{
    Response.Redirect("/home");
}

PassRegistration/Views/PassRegistration/Index.cshtml
@model IEnumerable<PassRegistration.Models.PassRegistration>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Pass Registrations</h2>

<p>
    @Html.ActionLink("Add Registration", "New")
</p>
<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th># In HouseHold</th>
                <th>Address</th>
                <th>City</th>
                <th>Phone No.</th>
                <th>Email</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var consultation in Model)
            {
                <tr>
                    <td>@consultation.Name</td>
                    <td>@consultation.NumberInHouse</td>
                    <td>@consultation.Address</td>
                    <td>@consultation.City</td>
                    <td>@consultation.PhoneNumber</td>
                    <td>@consultation.Email</td>
                    <td>@Html.ActionLink("Delete", "Delete", new { id = consultation.Id })</td>
                </tr>
            }
        </tbody>
    </table>

</div>

PassRegistration/Views/PassRegistration/New.cshtml
@model PassRegistration.Models.PassRegistration

@{
    ViewBag.Title = "New";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


 @if (User.Identity.Name.Length > 0)
 {



    <div class="col-lg-4">
        <br />
        <br />
        <br />
        <br />
        <img src="http://nebula.wsimg.com/7257c48b923bf090347611933235e1d6?AccessKeyId=9C55814FA3A2F565B863&disposition=0&alloworigin=1" />
        <br />
        <br />
        <p> The new recycling center is located at 800 Virginia Avenue Huntington WV at the old National Guard Armory.</p>
        <br />
        <h3>Recycling tips</h3>
        <p>Mix all items together – no separation required</p>
        <br />
        <p>Empty all bottles, jugs and cans</p>
        <p>No need to remove labels</p>
        <p>For plastic bottles, empty, crush and reattach lids</p>
        <p>For cartons, remove plastic caps and straws</p>
        <p>NEVER place medical sharps or needles in the recycling.</p>
        
    </div>

    <div class="col-lg-4">
        @using (Html.BeginForm("Add", "PassRegistration", FormMethod.Post, new { @class = "form"}))
        {
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <h2> </h2>
            <center>
                <h2>New Registration</h2>


                <div class="form-group">
                    @Html.LabelFor(m => m.Name)
                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control"  }  )
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.Address)
                    @Html.TextAreaFor(m => m.Address, new { @class = "form-control", rows = 4 })
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.NumberInHouse)
                    @Html.TextAreaFor(m => m.NumberInHouse, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.City)
                    @Html.TextBoxFor(m => m.City, new { @class = "form-control" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.PhoneNumber)
                    @Html.TextAreaFor(m => m.PhoneNumber, new { @class = "form-control", rows = 4 })
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.Email)
                    @Html.TextAreaFor(m => m.Email, new { @class = "form-control" }) 
                </div>

                <input type="submit" class="btn btn-primary" value="Save" />
            </center>
        }
    </div>

    <div class="col-lg-4">
        <br />
        <br />
        <br />
        <br />
        <img src="http://nebula.wsimg.com/7257c48b923bf090347611933235e1d6?AccessKeyId=9C55814FA3A2F565B863&disposition=0&alloworigin=1" />
        <br />
        <br />
        <h3> List of accepted items at the new recycling center:.</h3>
        <br />
        <p>Glass Bottles & Jars (all colors)</p>
        <p>Metal Cans:  Aluminum cans, steel cans and lids, empty aerosol cans with the lids and tips removed</p>
        <p>Plastic Bottles(empty, crush, reattach lid): Bottles and jugs that have a small mouth and wider base, such as milk jugs, soda bottles, laundry detergent bottles, water bottles, shampoo bottles and contact solution bottles</p>
        <p>Paper: newspaper, magazines, cardboard, mixed office paper and envelopes, paperboard (cereal boxes), pizza boxes free of food debris and grease, telephone books and catalogs</p>
        <p>Cartons: food and beverage cartons, such as milk, juice, soup, wine, broth and other cartons.</p>
        <br />
        

    </div>
 }
 else
{
    Response.Redirect("/Account/Login");
}